version: '3.3'

services:
    db:
        image: mysql:8.0.19
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: ['3306:3306']
        environment:
            # the image will only initialize the database if the data directory is empty
            MYSQL_DATABASE: starterkit
            MYSQL_USER: starterkit
            MYSQL_PASSWORD: starterkit
            MYSQL_ROOT_PASSWORD: starterkit
    test-db:
        image: mysql:8.0.19
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: ['6603:3306']
        environment:
            # the image will only initialize the database if the data directory is empty
            MYSQL_DATABASE: starterkit-test
            MYSQL_USER: starterkit
            MYSQL_PASSWORD: starterkit
            MYSQL_ROOT_PASSWORD: starterkit
    adminer:
        image: adminer
        restart: always
        ports: ['8888:8080']
    mailhog:
        image: mailhog/mailhog
        restart: always
        ports: ['1025:1025', '8025:8025']
    # https://docs.min.io/docs/minio-server-configuration-guide.html
    minio:
        image: minio/minio
        restart: always
        volumes: ['minio:/data']
        command: server /data
        ports: ['9000:9000']
        environment: 
            MINIO_ACCESS_KEY: starterkit
            MINIO_SECRET_KEY: starterkit
    minio-client:
        image: minio/mc
        volumes: ['./minio.init:/minio.init']
        entrypoint: sh
        depends_on: ['minio']
        command: /minio.init/init.sh
        environment: 
            MINIO_ACCESS_KEY: starterkit
            MINIO_SECRET_KEY: starterkit
            MINIO_BUCKET: starterkit.local
            MINIO_HOST: minio
            MINIO_PORT: 9000
            MINIO_IMAGES_DIR: images/
    # is used for images resize on fly
    # https://docs.imgproxy.net/#/
    imgproxy:
        image: darthsim/imgproxy:latest
        ports: ['5555:8080']
        depends_on: ['minio']
        environment: 
            IMGPROXY_DOWNLOAD_BUFFER_SIZE: 2097152
            IMGPROXY_ENABLE_WEBP_DETECTION: 'true'
            IMGPROXY_ENFORCE_WEBP: 'true'
            IMGPROXY_GZIP_BUFFER_SIZE: 1048576
            IMGPROXY_GZIP_COMPRESSION: 5
            IMGPROXY_KEY: 1111111111111111111111
            IMGPROXY_SALT: 1111111111111111111111
volumes:
    minio:
